//go:build !ignore_autogenerated
// +build !ignore_autogenerated

/*
Copyright 2022.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1

import (
	corev1 "k8s.io/api/core/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ContainerResourcePolicy) DeepCopyInto(out *ContainerResourcePolicy) {
	*out = *in
	if in.MinAllowed != nil {
		in, out := &in.MinAllowed, &out.MinAllowed
		*out = make(corev1.ResourceList, len(*in))
		for key, val := range *in {
			(*out)[key] = val.DeepCopy()
		}
	}
	if in.MaxAllowed != nil {
		in, out := &in.MaxAllowed, &out.MaxAllowed
		*out = make(corev1.ResourceList, len(*in))
		for key, val := range *in {
			(*out)[key] = val.DeepCopy()
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ContainerResourcePolicy.
func (in *ContainerResourcePolicy) DeepCopy() *ContainerResourcePolicy {
	if in == nil {
		return nil
	}
	out := new(ContainerResourcePolicy)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CrossVersionObjectReference) DeepCopyInto(out *CrossVersionObjectReference) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CrossVersionObjectReference.
func (in *CrossVersionObjectReference) DeepCopy() *CrossVersionObjectReference {
	if in == nil {
		return nil
	}
	out := new(CrossVersionObjectReference)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HorizontalScalePolicy) DeepCopyInto(out *HorizontalScalePolicy) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HorizontalScalePolicy.
func (in *HorizontalScalePolicy) DeepCopy() *HorizontalScalePolicy {
	if in == nil {
		return nil
	}
	out := new(HorizontalScalePolicy)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MetricSource) DeepCopyInto(out *MetricSource) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MetricSource.
func (in *MetricSource) DeepCopy() *MetricSource {
	if in == nil {
		return nil
	}
	out := new(MetricSource)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MetricStatus) DeepCopyInto(out *MetricStatus) {
	*out = *in
	if in.CurrentValue != nil {
		in, out := &in.CurrentValue, &out.CurrentValue
		x := (*in).DeepCopy()
		*out = &x
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MetricStatus.
func (in *MetricStatus) DeepCopy() *MetricStatus {
	if in == nil {
		return nil
	}
	out := new(MetricStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PredictiveHybridPodAutoscaler) DeepCopyInto(out *PredictiveHybridPodAutoscaler) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PredictiveHybridPodAutoscaler.
func (in *PredictiveHybridPodAutoscaler) DeepCopy() *PredictiveHybridPodAutoscaler {
	if in == nil {
		return nil
	}
	out := new(PredictiveHybridPodAutoscaler)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *PredictiveHybridPodAutoscaler) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PredictiveHybridPodAutoscalerList) DeepCopyInto(out *PredictiveHybridPodAutoscalerList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]PredictiveHybridPodAutoscaler, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PredictiveHybridPodAutoscalerList.
func (in *PredictiveHybridPodAutoscalerList) DeepCopy() *PredictiveHybridPodAutoscalerList {
	if in == nil {
		return nil
	}
	out := new(PredictiveHybridPodAutoscalerList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *PredictiveHybridPodAutoscalerList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PredictiveHybridPodAutoscalerSpec) DeepCopyInto(out *PredictiveHybridPodAutoscalerSpec) {
	*out = *in
	if in.ScaleTargetRef != nil {
		in, out := &in.ScaleTargetRef, &out.ScaleTargetRef
		*out = new(CrossVersionObjectReference)
		**out = **in
	}
	if in.Metrics != nil {
		in, out := &in.Metrics, &out.Metrics
		*out = new(MetricSource)
		**out = **in
	}
	if in.VerticalScalePolicy != nil {
		in, out := &in.VerticalScalePolicy, &out.VerticalScalePolicy
		*out = new(VerticalScalePolicy)
		(*in).DeepCopyInto(*out)
	}
	if in.HorizontalScalePolicy != nil {
		in, out := &in.HorizontalScalePolicy, &out.HorizontalScalePolicy
		*out = new(HorizontalScalePolicy)
		**out = **in
	}
	if in.Tolerance != nil {
		in, out := &in.Tolerance, &out.Tolerance
		*out = new(int32)
		**out = **in
	}
	if in.ScaleHistoryLimit != nil {
		in, out := &in.ScaleHistoryLimit, &out.ScaleHistoryLimit
		*out = new(int32)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PredictiveHybridPodAutoscalerSpec.
func (in *PredictiveHybridPodAutoscalerSpec) DeepCopy() *PredictiveHybridPodAutoscalerSpec {
	if in == nil {
		return nil
	}
	out := new(PredictiveHybridPodAutoscalerSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PredictiveHybridPodAutoscalerStatus) DeepCopyInto(out *PredictiveHybridPodAutoscalerStatus) {
	*out = *in
	if in.DesiredResourceRequirements != nil {
		in, out := &in.DesiredResourceRequirements, &out.DesiredResourceRequirements
		*out = make(map[string]corev1.ResourceRequirements, len(*in))
		for key, val := range *in {
			(*out)[key] = *val.DeepCopy()
		}
	}
	if in.MetricsList != nil {
		in, out := &in.MetricsList, &out.MetricsList
		*out = make([]MetricStatus, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.ScaleEventsList != nil {
		in, out := &in.ScaleEventsList, &out.ScaleEventsList
		*out = make([]ScaleEvent, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.LastHorizontalScaleTime != nil {
		in, out := &in.LastHorizontalScaleTime, &out.LastHorizontalScaleTime
		*out = (*in).DeepCopy()
	}
	if in.LastVerticalScaleTime != nil {
		in, out := &in.LastVerticalScaleTime, &out.LastVerticalScaleTime
		*out = (*in).DeepCopy()
	}
	if in.LastMonitorTime != nil {
		in, out := &in.LastMonitorTime, &out.LastMonitorTime
		*out = (*in).DeepCopy()
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PredictiveHybridPodAutoscalerStatus.
func (in *PredictiveHybridPodAutoscalerStatus) DeepCopy() *PredictiveHybridPodAutoscalerStatus {
	if in == nil {
		return nil
	}
	out := new(PredictiveHybridPodAutoscalerStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ScaleEvent) DeepCopyInto(out *ScaleEvent) {
	*out = *in
	if in.Time != nil {
		in, out := &in.Time, &out.Time
		*out = (*in).DeepCopy()
	}
	if in.Requirements != nil {
		in, out := &in.Requirements, &out.Requirements
		*out = make(map[string]corev1.ResourceRequirements, len(*in))
		for key, val := range *in {
			(*out)[key] = *val.DeepCopy()
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ScaleEvent.
func (in *ScaleEvent) DeepCopy() *ScaleEvent {
	if in == nil {
		return nil
	}
	out := new(ScaleEvent)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VerticalScalePolicy) DeepCopyInto(out *VerticalScalePolicy) {
	*out = *in
	if in.ContainerResourcePolicies != nil {
		in, out := &in.ContainerResourcePolicies, &out.ContainerResourcePolicies
		*out = make([]ContainerResourcePolicy, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.ServiceLabelSelector != nil {
		in, out := &in.ServiceLabelSelector, &out.ServiceLabelSelector
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VerticalScalePolicy.
func (in *VerticalScalePolicy) DeepCopy() *VerticalScalePolicy {
	if in == nil {
		return nil
	}
	out := new(VerticalScalePolicy)
	in.DeepCopyInto(out)
	return out
}
