//go:build !ignore_autogenerated
// +build !ignore_autogenerated

/*
Copyright 2022.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1

import (
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CrossVersionObjectReference) DeepCopyInto(out *CrossVersionObjectReference) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CrossVersionObjectReference.
func (in *CrossVersionObjectReference) DeepCopy() *CrossVersionObjectReference {
	if in == nil {
		return nil
	}
	out := new(CrossVersionObjectReference)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MetricSource) DeepCopyInto(out *MetricSource) {
	*out = *in
	if in.TargetAverageUtilization != nil {
		in, out := &in.TargetAverageUtilization, &out.TargetAverageUtilization
		*out = new(int32)
		**out = **in
	}
	if in.TargetAverageValue != nil {
		in, out := &in.TargetAverageValue, &out.TargetAverageValue
		x := (*in).DeepCopy()
		*out = &x
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MetricSource.
func (in *MetricSource) DeepCopy() *MetricSource {
	if in == nil {
		return nil
	}
	out := new(MetricSource)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MetricStatus) DeepCopyInto(out *MetricStatus) {
	*out = *in
	if in.CurrentUtilization != nil {
		in, out := &in.CurrentUtilization, &out.CurrentUtilization
		*out = new(int32)
		**out = **in
	}
	if in.CurrentValue != nil {
		in, out := &in.CurrentValue, &out.CurrentValue
		x := (*in).DeepCopy()
		*out = &x
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MetricStatus.
func (in *MetricStatus) DeepCopy() *MetricStatus {
	if in == nil {
		return nil
	}
	out := new(MetricStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PredictiveHorizontalPodAutoscaler) DeepCopyInto(out *PredictiveHorizontalPodAutoscaler) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PredictiveHorizontalPodAutoscaler.
func (in *PredictiveHorizontalPodAutoscaler) DeepCopy() *PredictiveHorizontalPodAutoscaler {
	if in == nil {
		return nil
	}
	out := new(PredictiveHorizontalPodAutoscaler)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *PredictiveHorizontalPodAutoscaler) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PredictiveHorizontalPodAutoscalerList) DeepCopyInto(out *PredictiveHorizontalPodAutoscalerList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]PredictiveHorizontalPodAutoscaler, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PredictiveHorizontalPodAutoscalerList.
func (in *PredictiveHorizontalPodAutoscalerList) DeepCopy() *PredictiveHorizontalPodAutoscalerList {
	if in == nil {
		return nil
	}
	out := new(PredictiveHorizontalPodAutoscalerList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *PredictiveHorizontalPodAutoscalerList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PredictiveHorizontalPodAutoscalerSpec) DeepCopyInto(out *PredictiveHorizontalPodAutoscalerSpec) {
	*out = *in
	out.ScaleTargetRef = in.ScaleTargetRef
	if in.MinReplicas != nil {
		in, out := &in.MinReplicas, &out.MinReplicas
		*out = new(int32)
		**out = **in
	}
	if in.MaxReplicas != nil {
		in, out := &in.MaxReplicas, &out.MaxReplicas
		*out = new(int32)
		**out = **in
	}
	if in.Metrics != nil {
		in, out := &in.Metrics, &out.Metrics
		*out = new(MetricSource)
		(*in).DeepCopyInto(*out)
	}
	if in.ScaleDownStabilizationWindowSeconds != nil {
		in, out := &in.ScaleDownStabilizationWindowSeconds, &out.ScaleDownStabilizationWindowSeconds
		*out = new(int32)
		**out = **in
	}
	if in.MonitorWindowIntervalNum != nil {
		in, out := &in.MonitorWindowIntervalNum, &out.MonitorWindowIntervalNum
		*out = new(int32)
		**out = **in
	}
	if in.Alpha != nil {
		in, out := &in.Alpha, &out.Alpha
		*out = new(string)
		**out = **in
	}
	if in.Tolerance != nil {
		in, out := &in.Tolerance, &out.Tolerance
		*out = new(string)
		**out = **in
	}
	if in.CpuInitializationPeriod != nil {
		in, out := &in.CpuInitializationPeriod, &out.CpuInitializationPeriod
		*out = new(string)
		**out = **in
	}
	if in.DelayOfInitialReadinessStatus != nil {
		in, out := &in.DelayOfInitialReadinessStatus, &out.DelayOfInitialReadinessStatus
		*out = new(string)
		**out = **in
	}
	if in.ScaleHistoryLimit != nil {
		in, out := &in.ScaleHistoryLimit, &out.ScaleHistoryLimit
		*out = new(int32)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PredictiveHorizontalPodAutoscalerSpec.
func (in *PredictiveHorizontalPodAutoscalerSpec) DeepCopy() *PredictiveHorizontalPodAutoscalerSpec {
	if in == nil {
		return nil
	}
	out := new(PredictiveHorizontalPodAutoscalerSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PredictiveHorizontalPodAutoscalerStatus) DeepCopyInto(out *PredictiveHorizontalPodAutoscalerStatus) {
	*out = *in
	if in.LastScaleTime != nil {
		in, out := &in.LastScaleTime, &out.LastScaleTime
		*out = (*in).DeepCopy()
	}
	if in.CurrentReplicas != nil {
		in, out := &in.CurrentReplicas, &out.CurrentReplicas
		*out = new(int32)
		**out = **in
	}
	if in.DesiredReplicas != nil {
		in, out := &in.DesiredReplicas, &out.DesiredReplicas
		*out = new(int32)
		**out = **in
	}
	if in.MetricsList != nil {
		in, out := &in.MetricsList, &out.MetricsList
		*out = make([]MetricStatus, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.ScaleEventsList != nil {
		in, out := &in.ScaleEventsList, &out.ScaleEventsList
		*out = make([]ScaleEvent, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.LastMonitorTime != nil {
		in, out := &in.LastMonitorTime, &out.LastMonitorTime
		*out = (*in).DeepCopy()
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PredictiveHorizontalPodAutoscalerStatus.
func (in *PredictiveHorizontalPodAutoscalerStatus) DeepCopy() *PredictiveHorizontalPodAutoscalerStatus {
	if in == nil {
		return nil
	}
	out := new(PredictiveHorizontalPodAutoscalerStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ScaleEvent) DeepCopyInto(out *ScaleEvent) {
	*out = *in
	if in.Time != nil {
		in, out := &in.Time, &out.Time
		*out = (*in).DeepCopy()
	}
	if in.Replicas != nil {
		in, out := &in.Replicas, &out.Replicas
		*out = new(int32)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ScaleEvent.
func (in *ScaleEvent) DeepCopy() *ScaleEvent {
	if in == nil {
		return nil
	}
	out := new(ScaleEvent)
	in.DeepCopyInto(out)
	return out
}
