# permissions for end users to edit predictivehorizontalpodautoscalers.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: predictivehorizontalpodautoscaler-editor-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: autoscaling
    app.kubernetes.io/part-of: autoscaling
    app.kubernetes.io/managed-by: kustomize
  name: predictivehorizontalpodautoscaler-editor-role
rules:
- apiGroups:
  - autoscaling.myw.domain
  resources:
  - predictivehorizontalpodautoscalers
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - autoscaling.myw.domain
  resources:
  - predictivehorizontalpodautoscalers/status
  verbs:
  - get
