---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - autoscaling.myw.domain
  resources:
  - predictivehybridpodautoscalers
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - autoscaling.myw.domain
  resources:
  - predictivehybridpodautoscalers/finalizers
  verbs:
  - update
- apiGroups:
  - autoscaling.myw.domain
  resources:
  - predictivehybridpodautoscalers/status
  verbs:
  - get
  - patch
  - update
